-- Reset data for a clean start (KEEP schema, only clear time-series / incident data)
-- Run this in your PostgreSQL database (e.g. psql, DBeaver, pgAdmin).
-- WARNING: This will delete ALL aggregated and incident data.

BEGIN;

-- Clear latest metrics
TRUNCATE TABLE system_metrics RESTART IDENTITY CASCADE;

-- Clear ETL aggregated sensor data
TRUNCATE TABLE sensor_data_aggregated RESTART IDENTITY CASCADE;

-- Clear incident alerts generated by ETL
TRUNCATE TABLE incident_alerts RESTART IDENTITY CASCADE;

-- Clear verified and official incidents (workflow data)
TRUNCATE TABLE official_incidents RESTART IDENTITY CASCADE;
TRUNCATE TABLE verified_incidents RESTART IDENTITY CASCADE;

COMMIT;

-- After running this script, run your ETL again so it repopulates:
--   python your_etl_script.py


